"""The knowledge-bundle trust boundary, and the contract with the external lab.

Two jobs.

**The contract.** ``tests/fixtures/research_lab/knowledge_bundle_v1.json`` is
generated by the lab's *actual exporter* — the same file is committed in both
repositories — so if either side's format drifts, this fails. (The candidate
bundle's equivalent fixture was hand-written to the contract while its docs
claimed otherwise; that lesson is why this one is generated.)

**The boundary.** The rest of this file is about what a file on disk is *not*
allowed to do. The Knowledge context feeds the AI Committee's training ledger,
so an inbox that trusted its input would be a way to train the platform on
whatever an external process asserted. The tests below pin the three structural
reasons that cannot happen:

* a bundle cannot declare its verification — the field does not exist, and the
  Core assigns `simulated` from the source;
* a bundle cannot claim a platform source (`paper_trading`, `executed_trade`, …)
  and so cannot pose as the trading path;
* a bundle cannot express a *lesson* at all, and lessons are the only thing the
  committee trains on.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import pytest

from hades.contexts.knowledge.domain.bundles import (
    BUNDLE_FORMAT,
    MAX_RECORDS,
    KnowledgeBundleRejectedError,
    canonical_checksum,
    parse_knowledge_bundle,
)
from hades.contexts.knowledge.domain.models import (
    KnowledgeKind,
    KnowledgeSource,
    SubjectType,
    Verification,
)

_FIXTURE = Path(__file__).parent / "fixtures" / "research_lab" / "knowledge_bundle_v1.json"
_AT = datetime(2026, 7, 28, 9, 30, tzinfo=UTC)


def _bundle(**overrides: Any) -> dict[str, Any]:
    """A minimal valid bundle, re-checksummed after any override."""
    payload: dict[str, Any] = {
        "bundle_format": BUNDLE_FORMAT,
        "bundle_id": "b-1",
        "produced_by": "hades-research-lab",
        "produced_at": _AT.isoformat(),
        "notes": "",
        "records": [
            {
                "source": "backtest",
                "kind": "simulation",
                "subject": "momentum_breakout",
                "subject_type": "strategy",
                "occurred_at": _AT.isoformat(),
                "payload": {"total_return": 0.34},
                "features": {"sharpe": 1.4},
                "correlation_id": None,
            }
        ],
    }
    payload.update(overrides)
    payload["checksum"] = canonical_checksum(payload)
    return payload


def _record(**overrides: Any) -> dict[str, Any]:
    base = _bundle()
    base["records"][0].update(overrides)
    base["checksum"] = canonical_checksum(base)
    return base


# --- the contract with the lab ------------------------------------------------


def test_the_fixture_written_by_the_labs_exporter_parses() -> None:
    """Both repositories commit this exact file. Drift on either side fails here."""
    bundle = parse_knowledge_bundle(json.loads(_FIXTURE.read_text(encoding="utf-8")))

    assert bundle.produced_by == "hades-research-lab"
    assert len(bundle) == 4
    subjects = {envelope.subject for envelope in bundle.envelopes}
    assert "momentum_breakout" in subjects
    sources = {envelope.source for envelope in bundle.envelopes}
    assert sources == {
        KnowledgeSource.BACKTEST,
        KnowledgeSource.WALK_FORWARD,
        KnowledgeSource.MONTE_CARLO,
        KnowledgeSource.RESEARCH_LAB,
    }


def test_the_checksum_is_computed_identically_on_both_sides() -> None:
    raw = json.loads(_FIXTURE.read_text(encoding="utf-8"))
    assert raw["checksum"] == canonical_checksum(raw)


# --- the boundary: what a file may not assert ---------------------------------


def test_every_external_record_is_labelled_simulated_regardless_of_source() -> None:
    """The single most important assertion in this file.

    `REALISED` means a trade that opened, ran and paid out, and the training path
    treats it as ground truth. If a backtest could stamp itself realised, the
    committee would train on the lab's assumptions and nothing downstream could
    tell the difference.
    """
    bundle = parse_knowledge_bundle(json.loads(_FIXTURE.read_text(encoding="utf-8")))
    assert {envelope.verification for envelope in bundle.envelopes} == {Verification.SIMULATED}


def test_a_bundle_cannot_declare_its_own_verification() -> None:
    """Not "ignored" — rejected. Silently dropping the field would leave a lab
    author believing they had asserted something."""
    with pytest.raises(KnowledgeBundleRejectedError, match="unknown keys"):
        parse_knowledge_bundle(_record(verification="realised"))


@pytest.mark.parametrize(
    "source", ["paper_trading", "executed_trade", "scanner", "security", "committee"]
)
def test_a_bundle_cannot_claim_a_platform_source(source: str) -> None:
    """A file on disk must not be able to pose as the platform observing itself."""
    with pytest.raises(
        KnowledgeBundleRejectedError, match="not accepted from an external producer"
    ):
        parse_knowledge_bundle(_record(source=source))


def test_a_bundle_cannot_claim_an_outcome_kind() -> None:
    """`OUTCOME` is the vocabulary of settled reality, not of a simulation."""
    with pytest.raises(
        KnowledgeBundleRejectedError, match="not accepted from an external producer"
    ):
        parse_knowledge_bundle(_record(kind="outcome"))


def test_the_bundle_format_has_no_way_to_express_a_lesson() -> None:
    """The structural backstop behind the two rules above.

    Lessons are what the committee trains on, and they are produced only by the
    Decision Journal settling a trade the platform actually took. Even a bundle
    that defeated every other check would still only be able to insert
    observations.
    """
    from hades.contexts.knowledge.domain import bundles

    surface = " ".join(bundles.__all__).lower()
    assert "lesson" not in surface
    bundle = parse_knowledge_bundle(_bundle())
    assert all(hasattr(envelope, "payload") for envelope in bundle.envelopes)
    assert not any(hasattr(envelope, "realized_roi") for envelope in bundle.envelopes)


# --- fail-closed parsing ------------------------------------------------------


def test_a_wrong_format_is_a_loud_rejection() -> None:
    with pytest.raises(KnowledgeBundleRejectedError, match="bundle_format"):
        parse_knowledge_bundle(_bundle(bundle_format="hades.knowledge/v2"))


def test_a_tampered_bundle_is_rejected_on_its_checksum() -> None:
    payload = _bundle()
    payload["records"][0]["payload"]["total_return"] = 9.99
    with pytest.raises(KnowledgeBundleRejectedError, match="checksum"):
        parse_knowledge_bundle(payload)


def test_unknown_top_level_keys_are_rejected_not_ignored() -> None:
    with pytest.raises(KnowledgeBundleRejectedError, match="unknown keys"):
        parse_knowledge_bundle(_bundle(deploy=True))


def test_non_finite_features_are_rejected() -> None:
    """NaN would poison anything computed from it, and JSON has no NaN — a
    producer emitting one has already produced a file no reader agrees on."""
    payload = _bundle()
    payload["records"][0]["features"] = {"sharpe": float("inf")}
    payload["checksum"] = canonical_checksum(payload)
    with pytest.raises(KnowledgeBundleRejectedError, match="finite"):
        parse_knowledge_bundle(payload)


def test_an_empty_bundle_is_rejected() -> None:
    with pytest.raises(KnowledgeBundleRejectedError, match="non-empty"):
        parse_knowledge_bundle(_bundle(records=[]))


def test_an_oversized_bundle_is_rejected_before_records_are_parsed() -> None:
    """Bounded so a single file cannot exhaust memory on the way in."""
    payload = _bundle(records=[{"junk": True}] * (MAX_RECORDS + 1))
    with pytest.raises(KnowledgeBundleRejectedError, match="exceeds"):
        parse_knowledge_bundle(payload)


def test_a_naive_timestamp_is_read_as_utc_not_local() -> None:
    """A naive timestamp silently shifts a research window by the host's offset."""
    payload = _record(occurred_at="2026-07-28T09:30:00")
    bundle = parse_knowledge_bundle(payload)
    assert bundle.envelopes[0].occurred_at.tzinfo is not None
    assert bundle.envelopes[0].occurred_at == _AT


def test_a_blank_subject_is_rejected() -> None:
    with pytest.raises(KnowledgeBundleRejectedError, match="subject"):
        parse_knowledge_bundle(_record(subject="   "))


def test_defaults_are_applied_for_optional_record_fields() -> None:
    payload = _bundle()
    payload["records"][0] = {
        "source": "research_lab",
        "kind": "experiment",
        "subject": "feature:holders.gini",
        "occurred_at": _AT.isoformat(),
    }
    payload["checksum"] = canonical_checksum(payload)
    envelope = parse_knowledge_bundle(payload).envelopes[0]
    assert envelope.subject_type is SubjectType.STRATEGY
    assert envelope.kind is KnowledgeKind.EXPERIMENT
    assert envelope.payload == {}
    assert envelope.features == {}
